name: got_key_scraping
channels:
  - conda-forge
  - defaults
dependencies:
  - selenium==3.13.0
  - webdriver-manager
  - fastapi=0.70.1=pyhd8ed1ab_0
  - uvicorn=0.15.0=py36h79c6626_1
  - contextlib2
